# Generated by Django 4.2.1 on 2023-06-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_mecanico_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecanico',
            name='test',
        ),
    ]
