# Generated by Django 4.2.1 on 2023-06-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_trabajo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trabajo',
        ),
    ]
