# Generated by Django 4.2.1 on 2023-06-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_delete_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trabajo', models.IntegerField()),
                ('rut_mecanico', models.IntegerField()),
                ('nombre_trabajo', models.CharField(max_length=70)),
                ('fecha_trabajo', models.DateField()),
                ('desc_trabajo', models.CharField(max_length=350)),
                ('diagnostico', models.CharField(max_length=50)),
                ('materiales_usados', models.CharField(max_length=100)),
                ('herr_usadas', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
