# Generated by Django 4.2.1 on 2023-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='foto',
            field=models.ImageField(null=True, upload_to='trabajos'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='motivo_desaprobacion',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
