# Generated by Django 4.2.1 on 2023-07-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_trabajo_foto_trabajo_motivo_desaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='correo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mecanico',
            name='passwd',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='rut_mecanico',
            field=models.CharField(max_length=10),
        ),
    ]
