# Generated by Django 4.2.1 on 2023-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_alter_trabajo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[['P', 'Pendiente'], ['A', 'Aprobado'], ['R', 'Rechazado']], max_length=1),
        ),
    ]
