# Generated by Django 4.2.1 on 2023-07-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_alter_trabajo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_postulacion', models.CharField(max_length=10)),
                ('rut_postulante', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('experiencia', models.CharField(max_length=200)),
                ('curriculum', models.ImageField(null=True, upload_to='curriculums')),
            ],
        ),
    ]
