# Generated by Django 4.2.1 on 2023-07-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_postulacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='id_postulacion',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='numero_tel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
