# Generated by Django 4.2.1 on 2023-07-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_rename_numero_tel_postulacion_numero_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postulacion',
            new_name='Postulacions',
        ),
    ]
