# Generated by Django 4.2.1 on 2023-07-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0014_rename_postulacion_postulacions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postulacions',
            new_name='Postulacion',
        ),
    ]
